import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { Sora, Geist_Mono } from "next/font/google";
import "./globals.css";

import { VisualEditingComponent } from '@/components/VisualEditing';

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const { isEnabled: isDraftMode } = await draftMode();

  return (
    <html
      lang="en"
      className={`${sora.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">{children}
        {isDraftMode && <VisualEditingComponent />}
      </body>
    </html>
  );
}
